from Sentents import Medic, Soldier

ScavengeTable:{str:int} = {
    "Wallet": 65,
    "Material": 65,
    "Bonus Material": 25,
    "Component": 35,
    "Bonus Component": 10,
    "Infantry": 5
}

RaidingTable = {
    "Material":65
}

MaterialTable:{str:tuple} = {
    "Water": (25, 30),
    "Sand": (17, 22),
    "Gravel": (17, 22),
    "Cotton": (15, 20),
    "Limestone": (14, 19),
    "Wheat": (13, 18),
    "Log": (12, 17),
    "Coal": (10, 15),
    "Mycelium": (9, 15),
    "Copper Ore": (7, 12),
    "Iron Ore": (7, 12),
    "Aluminum Ore": (5, 10),
    "Silver Ore": (3, 8),
    "Gold Ore": (1, 5),
    "Lithium Ore": (1, 3),
}

MaterialWorthTable:{str:float} = {
    "Water": 0.02,
    "Sand": 0.10,
    "Gravel": 0.10,
    "Cotton": 0.60,
    "Limestone": 0.65,
    "Wheat": 1.0,
    "Log": 1.2,
    "Coal": 3,
    "Mycelium": 5,
    "Copper Ore": 9,
    "Iron Ore": 9,
    "Aluminum Ore": 17,
    "Silver Ore": 28,
    "Gold Ore": 40,
    "Lithium Ore": 62,
}

InfantryToObject:{str:object} = {
    "Soldier":Soldier,
    "Medic":Medic,
}

InfantryTable:{str:int} = {
    "Level 1 ~ Soldier": 8500,
    "Level 2 ~ Soldier": 21500,
    "Level 3 ~ Soldier": 47300,
    "Level 1 ~ Medic": 8500,
    "Level 2 ~ Medic": 21500,
    "Level 3 ~ Medic": 47300,
    "Level 1 ~ Marksman": 8500,
    "Level 2 ~ Marksman": 21500,
    "Level 3 ~ Marksman": 47300,
}

# Values that are a tuple are: ({RecipeItem:Quantity,
#                                RecipeItem:Quantity}:
#                                OutputAmount)
# As the default output amount is 1, this allows the ability for some outputs to be multiple, like logs, or paper

Components = {"Copper":     {"Copper Ore":4},
              "Iron":       {"Iron Ore":4},
              "Aluminum":   {"Aluminum Ore":5},
              "Lithium":    {"Lithium Ore":2},
              "Bread":      {"Wheat":12},
              "Lumber":     ({"Log":1},
                              4),
              "Paper":      ({"Log":1},
                              36),
              "Fabric":     {"Cotton":8},
              "Clothes":    {"Fabric":4},
              "Concrete":   {"Water":12,
                             "Limestone":4,
                             "Gravel":4},
              "Steel":      {"Coal":4,
                             "Iron":4},
              "Plastic":    {"Oil":6},
              "Fuel":       {"Oil":9},
              "Silicone":   {"Coal":2,
                             "Sand":6},
              "Wire":       ({"Copper":1},
                              8),
              "Batteries":  {"Copper":2,
                             "Aluminum":4,
                             "Lithium":3},
              "Bullets":    {"Copper":1,
                             "Iron":2,
                             "Steel":1},
              "Firearms":   {"Iron":10,
                             "Aluminum":5,
                             "Steel":4,
                             "Plastic":4},
              "Med-kits":   {"Fabric":10,
                             "Paper":12,
                             "Steel":12,
                             "Plastic":8},}

Weapons = {"Tier 1 Missile":{"Copper":500,
                             "Iron":500,
                             "Aluminum":360,
                             "Steel":280,
                             "Wire":400,
                             "Fuel":205},
           "Tier 2 Missile":{"Copper":1250,
                             "Iron":1250,
                             "Aluminum":920,
                             "Steel":685,
                             "Wire":860,
                             "Fuel":465},
           "Tier 3 Missile":{"Copper":2900,
                             "Iron":2900,
                             "Aluminum":2360,
                             "Steel":1545,
                             "Wire":1880,
                             "Fuel":720},
           "Tier 4 Missile":{"Copper":6400,
                             "Iron":6400,
                             "Aluminum":5450,
                             "Steel":3740,
                             "Wire":4000,
                             "Fuel":1310},
           "Tier 5 Missile":{"Copper":144000,
                             "Iron":144000,
                             "Aluminum":133000,
                             "Steel":7980,
                             "Wire":8200,
                             "Fuel":3610},
           "Tier 1 Shield":{"Copper":500,
                             "Iron":500,
                             "Aluminum":360,
                             "Steel":280,
                             "Wire":400,
                             "Batteries":180},
           "Tier 2 Shield":{"Copper":1250,
                             "Iron":1250,
                             "Aluminum":920,
                             "Steel":685,
                             "Wire":860,
                             "Batteries":420},
           "Tier 3 Shield":{"Copper":2900,
                             "Iron":2900,
                             "Aluminum":2360,
                             "Steel":1545,
                             "Wire":1880,
                             "Batteries":860},
           "Tier 4 Shield":{"Copper":6400,
                             "Iron":6400,
                             "Aluminum":5450,
                             "Steel":3740,
                             "Wire":4000,
                             "Batteries":1920},
           "Tier 5 Shield":{"Copper":144000,
                             "Iron":144000,
                             "Aluminum":133000,
                             "Steel":7980,
                             "Wire":8200,
                             "Batteries":4250},
           "Tier 1 EMP":{"Iron": 600,
                         "Copper": 900,
                         "Aluminum":450,
                         "Wire":750,
                         "Batteries":400},
           "Tier 2 EMP":{"Iron": 1450,
                         "Copper": 1980,
                         "Aluminum":1000,
                         "Wire":1700,
                         "Batteries":960},
           "Tier 3 EMP":{"Iron": 3400,
                         "Copper": 3900,
                         "Aluminum":1550,
                         "Wire":3725,
                         "Batteries":2000},}

TypeMapping = {"Components":Components,
           "Weapons":Weapons}